version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "40000:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: always
    networks:
      - ollama-net

  ollama-reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: bartolli497/xcaddy-auth:ollama
    container_name: ollama-reverse-proxy-server
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - ollama-net
    volumes:
      - ./server-logs:/var/log

volumes:
  open-webui:

networks:
  ollama-net:
    driver: bridge
    name: ollama-net
    external: false
